import { IPluginConstructor } from "../plugin-api";
import { IPluginContext, generatePluginRuntimeContext } from "./plugin-runtime-context";

const pluginError = (e: string, other: any) => {
  // tslint:disable-next-line:no-console
  console.group("LARA Plugin Error");
  // tslint:disable-next-line:no-console
  console.error(e);
  // tslint:disable-next-line:no-console
  console.dir(other);
  // tslint:disable-next-line:no-console
  console.groupEnd();
};

/** @hidden Note, we call these `classes` but any constructor function will do. */
const pluginClasses: { [label: string]: IPluginConstructor } = {};

/**
 * Called in plugins/_show.haml before each plugin is loaded.  The value is used by #registerPlugin
 * to override the plugin's passed label.  This removes the previous need for the plugin's label to
 * match the label in LARA's database.
 */
let nextPluginLabel: string = "";
export const setNextPluginLabel = (override: string) => {
  nextPluginLabel = override;
};

/****************************************************************************
 Note that this method is NOT meant to be called by plugins. It's used by LARA internals.
 This method is called to initialize the plugin.
 Called at runtime by LARA to create an instance of the plugin as would happen in `views/plugin/_show.html.haml`.
 @param label The the script identifier.
 @param context Initial plugin context generated by LARA. Will be transformed into IPluginRuntimeContext instance.
 ****************************************************************************/
export const initPlugin = (label: string, context: IPluginContext) => {
  const Constructor: IPluginConstructor = pluginClasses[label];
  if (typeof Constructor === "function") {
    try {
      const plugin = new Constructor(generatePluginRuntimeContext(context));
    } catch (e) {
      pluginError(e, context);
    }
    // tslint:disable-next-line:no-console
    console.info("Plugin", label, "is now registered");
  } else {
    // tslint:disable-next-line:no-console
    console.error("No plugin registered for label:", label);
  }
};

/****************************************************************************
 Register a new external script as `label` with `_class `, e.g.:
 ```
 registerPlugin('debugger', Dubugger)
 ```
 @param deprecratedLabel DEPRECATED: The identifier of the script.
 @param _class The Plugin class/constructor being associated with the identifier.
 @returns `true` if plugin was registered correctly.
 ***************************************************************************/
export const registerPlugin = (deprecratedLabel: string, _class: IPluginConstructor): boolean => {
  if (nextPluginLabel === "") {
    // tslint:disable-next-line:no-console
    console.error("nextPluginLabel not set via #setNextPluginLabel before plugin loaded!");
    return false;
  }
  if (typeof _class !== "function") {
    // tslint:disable-next-line:no-console
    console.error("Plugin did not provide constructor", nextPluginLabel);
    return false;
  }
  if (pluginClasses[nextPluginLabel]) {
    // tslint:disable-next-line:no-console
    console.error("Duplicate Plugin for label", nextPluginLabel);
    return false;
  } else {
    pluginClasses[nextPluginLabel] = _class;
    nextPluginLabel = "";
    return true;
  }
};
