#
# add this after docker-compose-portal-proxy.yml to switch to https.
#
# Example in .env:
#
# COMPOSE_FILE=docker-compose.yml:docker/dev/docker-compose-portal-proxy.yml:docker/dev/docker-compose-portal-https-proxy.yml:...
#
version: '3'
services:
  app:
    environment:
      CONCORD_LOCALHOST_URL: https://${PORTAL_HOST}/
