# an image to verify sane DNS & NFS setup:
web:
  image: kitematic/hello-world-nginx
  environment:
    VIRTUAL_HOST: hello.dev
  ports:
    - "80:80"
  volumes:
    - ./hello_website/:/website_files

mysql:
  image: mysql/mysql-server:5.6
  ports:
    - "3306"
  environment:
    VIRTUAL_HOST: mysql.dev
    MYSQL_ROOT_PASSWORD: admin123H

# The rails app
app:
  build: .
  command: ./script/docker-app.sh
  environment:
    DB_HOST: mysql.dev
    DB_USER: root
    DB_PASSWORD: admin123H
    DB_NAME: lara
  ports:
    - "3000:3000"
  volumes:
    - /vagrant:/myapp
  links:
    - mysql
    - mysql:mysql.dev
