# The rails app
app:
  container_name: app
  build: .
  command: ./script/docker-app.sh
  environment:
    # NOTE: empty environment variables inherit their values from the host
    VIRTUAL_HOST: app.lara
    DB_HOST:
    DB_USER:
    DB_PASSWORD:
    DB_NAME:
    DOCKER_PORTAL_NAME:
    CONCORD_DOCKER_URL:
    CONCORD_DOCKER_CLIENT_ID:
    CONCORD_DOCKER_CLIENT_SECRET:
  ports:
    - "80:3000"
  volumes:
    - .:/lara

worker:
  container_name: worker
  image: lara_app
  command: ruby ./script/delayed_job_docker start
  environment:
    # NOTE: empty environment variables inherit their values from the host
    DB_HOST:
    DB_USER:
    DB_PASSWORD:
    DB_NAME:
