# set base ruby image
FROM ruby:3.3.7

# update repositories
RUN echo 'deb http://archive.debian.org/debian/ stretch main' > /etc/apt/sources.list
RUN apt-get update

# install needed packages
RUN apt-get install -y build-essential libpq-dev nodejs

#
# Install wait-for-it to support docker-volume-sync
WORKDIR /usr/local/bin
RUN wget https://raw.githubusercontent.com/vishnubob/wait-for-it/db049716e42767d39961e95dd9696103dca813f1/wait-for-it.sh && \
    chmod +x wait-for-it.sh

# Install phatomjs for javascript testing in docker
ENV PHANTOMJS_VERSION 1.9.8

RUN curl -SLO "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2" \
	&& tar -xjf "phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2" -C /usr/local --strip-components=1 \
	&& rm "phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2"

ENV APP_HOME /lara
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# use a mounted volume so the gems don't need to be rebundled each time
ENV BUNDLE_PATH /bundle

ADD . .

EXPOSE 3000

CMD rails s -b 0.0.0.0
