# Simply to test port forwarding &etc.
web:
  image: kitematic/hello-world-nginx
  ports:
    - "8888:80"
  volumes:
    - ./hello_website/:/website_files

mysql:
  image: mysql/mysql-server:5.6
  ports:
    - "3306"
  environment:
    VIRTUAL_HOST: mysql.dev
    MYSQL_ROOT_PASSWORD: admin123H
  volumes_from:
    - data


# The rails app
app:
  build: .
  command: ./script/docker-app.sh
  environment:
    DB_HOST: mysql.dev
    DB_USER: root
    DB_PASSWORD: admin123H
    DB_NAME: lara
  ports:
    - "3000:3000"
  volumes:
    - /lara:/lara
  links:
    - mysql
    - mysql:mysql.dev

data:
  image: busybox
  volumes:
    - /var/lib/mysql
