FROM concordconsortium/docker-rails-base-ruby-2.2.6

ENV APP_HOME /lara
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# use a mounted volume so the gems don't need to be rebundled each time
ENV BUNDLE_PATH /bundle

ADD . .

EXPOSE 3000

CMD rails s -b 0.0.0.0
