import {
  IRuntimeContext, IRuntimeContextExperimentalFeatures, IJwtResponse, IClassInfo, IInteractiveState
} from "../api/types";

/** Data generated by LARA, passed to .initPlugin function, and then used to generate final IRuntimeContext */
export interface IPluginContext {
  /** Name of the plugin */
  name: string;
  /** Url from which the plugin was loaded. */
  url: string;
  /** Active record ID of the plugin scope id. */
  pluginId: string;
  /** The authored configuration for this instance. */
  authoredState: string;
  /** The saved learner data for this instance. */
  learnerState: string;
  /** URL used to save plugin state. */
  learnerStateSaveUrl: string;
  /** Reserved HTMLElement for the plugin output. */
  div: HTMLElement;
  /** The run ID for the current run. */
  runId: number;
  /** The current users email address if available. */
  userEmail: string;
  /** The portal URL for class details (if available, empty string otherwise). */
  classInfoUrl: string;
  /** The portal remote endpoint (if available). */
  remoteEndpoint: string;
  /** Interactive state URL, available only when plugin is wrapping an interactive (empty string otherwise). */
  interactiveStateUrl: string;
  /** URL to fetch a JWT. Includes generic `_FIREBASE_APP_` that should be replaced with app name. */
  firebaseJwtUrl: string;
  /** Wrapped embeddable container, available only when plugin is wrapping an interactive. */
  wrappedEmbeddableDiv: HTMLElement | undefined;
  /****************************************************************************
   When plugin is wrapping an embeddable, this field will contain its properties - serialized
   form of the embeddable, e.g.:
   ```
   {
     aspect_ratio_method: "DEFAULT",
     authored_state: null,
     click_to_play: false,
     enable_learner_state: true,
     name: "Test Interactive",
     native_height: 435,
     native_width: 576,
     url: "http://concord-consortium.github.io/lara-interactive-api/iframe.html",
     type: "MwInteractive",
     ref_id: "86-MwInteractive"
   }
   ```
   ****************************************************************************/
  wrappedEmbeddableContext: any | null;
  experimental: IRuntimeContextExperimentalFeatures;
}

const getFirebaseJwt = (firebaseJwtUrl: string, appName: string): Promise<IJwtResponse> => {
  return new Promise((resolve, reject) => {
    const appSpecificUrl = firebaseJwtUrl.replace("_FIREBASE_APP_", appName);
    fetch(appSpecificUrl, {method: "POST"})
      .then(response => {
        response.json()
          .then((data) => {
            try {
              const token = data.token.split(".")[1];
              const claimsJson = atob(token);
              const claims = JSON.parse(claimsJson);
              resolve({token: data.token, claims});
            } catch (error) {
              // tslint:disable-next-line:no-console
              console.error("unable to parse JWT Token");
              // tslint:disable-next-line:no-console
              console.error(error);
            }
            resolve({token: data, claims: {}});
          });
      });
  });
};

const getClassInfo = (classInfoUrl: string): Promise<IClassInfo> | null => {
  if (!classInfoUrl) {
    return null;
  }
  return new Promise((resolve, reject) => {
    fetch(classInfoUrl, {method: "get", credentials: "include"})
      .then(resp => resp.json().then( (data) => resolve(data)));
  });
};

const getInteractiveState = (interactiveStateUrl: string): Promise<IInteractiveState> | null => {
  if (!interactiveStateUrl) {
    return null;
  }
  return new Promise((resolve, reject) => {
    fetch(interactiveStateUrl, {method: "get", credentials: "include"})
      .then(resp => resp.json().then((data) => resolve(data)));
  });
};

const getReportingUrl = (interactiveStateUrl: string): Promise<string | null> | null => {
  if (!interactiveStateUrl) {
    return null;
  }
  return getInteractiveState(interactiveStateUrl)!.then(interactiveState => {
    try {
      const rawJSON = JSON.parse(interactiveState.raw_data);
      if (rawJSON && rawJSON.lara_options && rawJSON.lara_options.reporting_url) {
        return rawJSON.lara_options.reporting_url;
      }
      return null;
    }
    catch (e) {
      // tslint:disable-next-line:no-console
      console.error(e);
      return null;
    }
  });
};

export const generateRuntimeContext = (context: IPluginContext): IRuntimeContext => {
  return {
    name: context.name,
    url: context.url,
    pluginId: context.pluginId,
    authoredState: context.authoredState,
    learnerState: context.learnerState,
    div: context.div,
    runId: context.runId,
    userEmail: context.userEmail,
    remoteEndpoint: context.remoteEndpoint,
    wrappedEmbeddableDiv: context.wrappedEmbeddableDiv,
    wrappedEmbeddableContext: context.wrappedEmbeddableContext,
    experimental: context.experimental,
    getFirebaseJwt: (appName: string) => getFirebaseJwt(context.firebaseJwtUrl, appName),
    getInteractiveState: () => getInteractiveState(context.interactiveStateUrl),
    getReportingUrl: () => getReportingUrl(context.interactiveStateUrl),
    getClassInfo: () => getClassInfo(context.classInfoUrl)
  };
};
