#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '../..', 'config', 'environment'))
require 'delayed/command'
Delayed::Command.new(ARGV).daemonize

# sleep so the Docker container doesn't die
sleep
