modulejs.define 'components/itsi_authoring/model_list',
->
  # from https://learn.staging.concord.org/interactives/export_model_library
  return [
    {
      "name": "Conduction A - wood vs metal",
      "description": "<p>Compare the conduction of wood and metal, using Energy2D.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/energy2d\/conduction-wood-metal.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/10.png",
      "credits": "Charles Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Conduction B - area",
      "description": "<p>Compare the conduction through larger and smaller areas.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/energy2d\/conduction-area.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/11.png",
      "credits": "Charles Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Conduction C - Temperature Difference",
      "description": "<p>Explore the effect of temperature difference on the amount of heat flow.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/energy2d\/conduction-temperature-difference.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/12.png",
      "credits": "Charles Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Conduction D - heat capacity",
      "description": "<p>Explore the effect of heat capacity on heat transfer through a material.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/energy2d\/conduction-heat-capacity.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/13.png",
      "credits": "Charles Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Heat and Temperature  7: Thermal Radiation (SAM)",
      "description": "<p>Students explore the transfer of heat by photons. In the model, one can heat the material in a first compartment, which will then emit photons. Some photons will travel to the material in a second compartment, be absorbed and heat it up.<\/p>\r\n<p>WHAT TO DO: 1) Click the \"Run\" button to start the model and THEN click the \"Heat the yellow atoms\" button multiple times until you note that there are dotted lines around certain atoms. Those atoms are now excited and will emit photons. 2) Click the \"K.E. Shading\" button. 3) Watch what happens to the kinetic energy of the solid on the left side of the model.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/heat-and-temperature\/heat-and-temperature-7.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/16.png",
      "credits": "Dan Damelin and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Atomic Structure 6 and Photons 2a: The shape of the orbitals depends on the electron energy (SAM) Itsisu",
      "description": "<p>Atoms have a ground state and many excited states for its electrons. This is a model of a hydrogen atom. It has only one electron.  The 1s orbital represents the region where you are likely to find that electron. By adding energy to the electron (with light, heat, or some other source) you can make that electron have more energy, which means the pattern where you find it around the nucleus will change.<\/p>\r\n<p>WHAT TO DO: Try clicking on the various energy levels\/orbitals in the chart (click on the gray bar - be sure to touch the gray bar itself with the \"fingertip\" of the cursor) to put the electron at that energy level and see an interactive 3D view of that orbital.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/jsmol\/energy-levels.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/25.png",
      "credits": "Dan Damelin, George Collison and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Atomic Structure 6 and Photons 2a: The Shape of the Orbitals and Electron Energy (SAM)  (a)",
      "description": "<p>Atoms have a ground state and many excited states for its electrons. This is a model of a hydrogen atom. It has only one electron.  The 1s orbital represents the region where you are likely to find that electron. By adding energy to the electron (with light, heat, or some other source) you can make that electron have more energy, which means the pattern where you find it around the nucleus will change.<\/p>\r\n<p>WHAT TO DO: Try clicking on the various energy levels\/orbitals in the chart (click on the gray bar - be sure to touch the gray bar itself with the \"fingertip\" of the cursor) to put the electron at that energy level and see an interactive 3D view of that orbital.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/jsmol\/energy-levels.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/26.png",
      "credits": "Dan Damelin, George Collison and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Gas Laws 1: What is pressure? (SAM)",
      "description": "<p>The  model shows molecules inside and outside a very tiny section of a balloon. The rectangle in the middle represents the balloon's cross-section. The arrows on the molecules represent their velocities.<\/p>\r\n<p>WHAT TO DO:  Press the \"Run\" button.  Use the \"Add...\" and \"Remove...\" buttons to change the number of atoms in the balloon. Important: After you add or remove atoms, run the model for a minute so that it can have enough time to respond to your changes.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/gas-laws\/2-what-is-pressure.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/29.png",
      "credits": "Dan Damelin and the Molecular Workbench team;  Model-Builder (Molecular Workbench): Qian Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "The Pressure-Temperature Relationship (Gay-Lussac) (bar graph)",
      "description": "<p>The Gay-Lussac Law is that the pressure of a gas of fixed mass and fixed volume is directly proportional to the gas's absolute temperature. In the model  a virtual gauge is placed in the container of gas to measure pressure. The output is shown with a bar graph.<\/p>\n<p>WHAT TO DO: Run until the simulation automatically stops, and then change temperature using the slider below and run again. Repeat a few times.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/gas-laws\/5-temperature-pressure-relationship.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/30.png",
      "credits": "Dan Damelin and the Molecular Workbench team;  Model-Builder (Molecular Workbench): Charles Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Gas Laws 5: (Avogadro's Number) the number-volume relationship (SAM)  (no graph)",
      "description": "<p>This model allows you to run a series of trials, one right after another, each time changing the number of molecules of gas and observing how the volume is affected. The model initially contains 120 molecules. The piston is not in a fixed position; it can move so as to maintain a constant pressure. The number on the piston shows the length of the gas chamber. Since this is a two-dimensional model, what we are calling \"volume\" of the gas is really the length of the chamber (in &Atilde;&hellip;).<\/p>\n<p>WHAT TO DO:   (1) Click Run. Observe any changes in the volume of the chamber. Click Stop after letting the model run for at least 30 seconds or until the piston just jiggles in the same place.   (2) Note the average volume of the container (the number inside the red rectangle.)   (3) Select the other five radio buttons (\"100 molecules\", etc.) and repeat (1) and (2) for each trial.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/gas-laws\/6-number-volume-relationship.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/31.png",
      "credits": "Dan Damelin and the Molecular Workbench team;  Model-Builder (Molecular Workbench): Charles Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Gas Laws 6:  A soda can implodes (SAM)",
      "description": "<p>The model is an incomplete model of a soda can. Currently it is showing gas molecules inside and outside the soda can before it is plunged in ice water. The gray rectangle in the middle of the model represents a micro-section of the soda can wall.   Design a model that shows what happens after the can is placed in ice water. Use the tools above the model to more accurately represent the experiment. Use tools to heat and cool the molecule where it is appropriate. The explanations of the tools are in the gray box to the left of the model.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/gas-laws\/7b-why-did-the-can-collapse.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/32.png",
      "credits": "Dan Damelin and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "DNA to Proteins: Making mutations (SAM)",
      "description": "<p>This model can be used to make a number of mutations: substitution, silent, frame shift, as well as stop codons, that stop the replication process.<\/p>\n<p>WHAT TO DO: 1. Replace one nucleotide with another for a substitution mutation. To make a mutation, right-click on a nucleotide. Then choose a mutation from the pop-up menu. (For example, you can change  TTT to TCT.) 2. Add an extra nucleotide in the DNA sequence for an insertion mutation. 3. Delete a nucleotide for a deletion mutation.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/protein-structure\/dna-mutations.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/52.png",
      "credits": "Boris Berenfeld and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Heat of Reactions - Explosion Model 1",
      "description": "",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/heats-of-reaction\/explosion-model-1.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/53.png",
      "credits": "Dan Damelin and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Heat of Reactions - Explosion Model 2",
      "description": "<p>HOLD Heat and Cool buttons down to affect the rate of reactions.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/heats-of-reaction\/explosion-model-2.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/54.png",
      "credits": "The Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Heat of Reactions - Explosion Model 4",
      "description": "<p>A model that allows the exploration of the effect of temperature on kinetic movement of particles and their effect, in turn, on pressure.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/heats-of-reaction\/explosion-model-4.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/55.png",
      "credits": "Dan Damelin and the Molecular Workbench team;  Model-Builder (Molecular Workbench): Charles Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Activation Energy  1: Energy Exchange in Collision and, perhaps, a Reaction",
      "description": "<p>This model allows the user to observe the exchange of kinetic and potential energy between an atom and a molecule in a collision. Reaction is rare.  Along the reaction path, the potential energy of the system is usually higher than those of the initial and final states. This makes a transition barrier for the system. As a result, the system needs to gain some energy in order to surmount the barrier and reach the final state. This minimum of this energy is called the activation energy.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/chemical-reactions\/activation-energy-1.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/56.png",
      "credits": "Charles Xie and the Molecular Workbench",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Activation Energy 2: More Activation Energy",
      "description": "<p>This is a model of a chemical reaction when an atom collides under certain circumstances with a molecule.  Users can observe how the potential energy is converted to kinetic energy during a new bond formation by looking at the graph next to the model. This model can be used with others in the Activation Energy sequence, illustrating the impact of high activation energy.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/chemical-reactions\/activation-energy-2.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/57.png",
      "credits": "Charles Xie and the Molecular Workbench",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Activation Energy 3:  Less Activation Energy",
      "description": "<p>This is a model of a chemical reaction after a collision between an atom and a molecule. Circumstances in this model are favorable for a chemical reaction as the activation energy is set low. This model can be used with others in the Activation Energy sequence.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/chemical-reactions\/activation-energy-3.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/58.png",
      "credits": "Charles Xie and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Activation Energy 4: Larger Activation Energy, with Temperature Control",
      "description": "<p>This model is useful in a sequence of models teaching levels of activation energy. While appearing like the others, its atoms actually have higher activation energy.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/chemical-reactions\/activation-energy-4.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/59.png",
      "credits": "Charles Xie and the Molecular Workbench",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Making and Breaking Bonds: A + A --> A2",
      "description": "<div id=\"content\" style=\"text-align: left;\">This activity will allow you to explore reactions in which chemical bonds are formed and broken in the reaction&nbsp; A + A --&gt; A2. How does temperature affect the rate of chemical reactions?<\/div>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/chemical-reactions\/making-breaking.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/69.png",
      "credits": "Dan Damelin and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Making and Breaking Bonds 3: Dissociation Energy A2<-->2A",
      "description": "<p>Experiment with the forces at work when two atoms come together to make a single molecule. Users can turn on Kinetic Energy by clicking the box below the model, can adjust the temperature and change the dissociation energy.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/chemical-reactions\/dissocation-energy.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/71.png",
      "credits": "Dan Damelin and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Reaction Kinetics: Normal equation",
      "description": "<p>The model demonstrates a most simple reaction in which two atoms bond together to make a molecule.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/reaction-kinetics\/normal.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/73.png",
      "credits": "Dan Damelin and Molecular Workbench Team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Chemical Reactions 2: How does concentration affect reaction rate? (SAM)",
      "description": "<p>The model depicts a reaction in which two atoms are bonded together to make a molecule. Users can experiment  with changing the concentration of the atoms in order to see how this affects the reaction rate (the speed in which the reaction happens).<\/p>\r\n<p>WHAT TO DO: 1. Add some atoms (press multiple times to add more)     2. Run the model.  3. Reset the model and try a different concentration.  Gauge the reaction speed by using the graph to see when the reaction reaches 80% completion.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/chemical-reactions\/2-concentration-reaction-rate.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/74.png",
      "credits": "Dan Damelin, with the Molecular Workbench team; Model-builder (Molecular Workbench): Qian Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Chemical Reactions 4: Container size challenge (SAM)",
      "description": "<p>This is a challenge model: Using your knowledge of reaction rates, see how fast you can get the reaction below to reach and sustain 80% completion or better.<\/p>\r\n<p>WHAT TO DO: START by adding atoms, running the model and watching the temperature.  RESET the container and then change the size of the container by writing a new dimension, e.g. 100, 250, in the \"change container size\" space.in the the \"change container size\" button below. (Note: You can ONLY resize the container when it is empty. To empty the container use the \"reset\" button.)  You can only add 10 atoms to the container.  You can change the temperature by using the slider.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/chemical-reactions\/4-container-size-challenge.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/75.png",
      "credits": "Dan Damelin, with the Molecular Workbench team; Model-builder (Molecular Workbench): Qian Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Chemical Reactions 7: Limiting reactions (SAM)",
      "description": "<p>An exploration of the reactant that gets used up first, called a \"limiting reactant\".<\/p>\r\n<p>WHAT TO DO: Compare the difference between a combustion reaction that has the exact ratio of reactants with a reaction that has a limiting reactant. See if you can tell which reactant is considered the \"limiting reactant\" in the 2nd model.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/chemical-reactions\/7-limiting-reactions.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/76.png",
      "credits": "Dan Damelin, with the Molecular Workbench team; Model-builder (Molecular Workbench): Qian Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "From Stoichiometry: Constructing Water Molecules",
      "description": "<p>You can construct two water molecules by pulling the atoms into position.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/stoichiometry\/constructucting-water-molecules.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/77.png",
      "credits": "",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "From Stoichiometry: Constructing a Larger Number of  Water Molecules",
      "description": "<p>Construct a number of water molecules.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/stoichiometry\/constructing-a-larger-number-of-water-molecules.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/78.png",
      "credits": "",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Chemical Reactions 6: Getting the correct ratio of hydrogen and oxygen (SAM)",
      "description": "<p>This model presents an opportunity an opportunity to balance the equation for water.<\/p>\r\n<p>WHAT TO DO: Using the menus below, experiment with determining the correct ratio of hydrogen to oxygen to water. <strong>NOTE 1: <\/strong> You will have to set both the oxygen and the hydrogen before the model will appear. <strong>NOTE 2:<\/strong> More than one ratio will work so that water is produced, using up all of the reactants. However, only one ratio is the simplest.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/stoichiometry\/correct-ratio-of-hydrogen-and-oxygen.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/79.png",
      "credits": "Dan Damelin and the Molecular Workbench team; Molecular Workbench: Charles Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "From Stoichiometry: Most ammonia molecules",
      "description": "",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/stoichiometry\/most-ammonia-molecules.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/80.png",
      "credits": "",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Chemical Reactions 5: Getting the ratios right (SAM)",
      "description": "<p>The model provides an opportunity to explore chemical ratios. There are several ratios of hydrogen to chlorine that will satisfy the two laws (the law of conservation and the law of definite proportions.) However, they all can be simplified to the 1:1:2 ratio you see in the balanced equation:    H2 + Cl2  2 HCl<\/p>\r\n<p>WHAT TO DO: Try several different ratios to see which ones form a complete reaction with nothing left over. Select a ratio and observe the model. Try several different ratios to see which ones form a complete reaction with nothing left over:<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/stoichiometry\/getting-ratios-right.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/81.png",
      "credits": "Dan Damelin, with the Molecular Workbench team; Model-builder (Molecular Workbench): Qian Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Chemical Reactions 8:  Choosing a reaction (SAM)",
      "description": "<p>Test yourself to see if you can determine the type of reaction shown in the model container. There are three different reactions.<\/p>\r\n<p>WHAT TO DO: Select a reaction and then determine whether each reaction is an example of synthesis, decomposition, single displacement or double displacement.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/stoichiometry\/choosing-a-reaction.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/82.png",
      "credits": "Dan Damelin and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Electrostatics: Lab applications (SAM)",
      "description": "<p>Three types of electroscopes show how an electroscope detects and evaluates charge on objects.<\/p>",
      "url": "https:\/\/models-resources.concord.org\/md2d\/electroscopes.html",
      "width": 660,
      "height": 380,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/95.png",
      "credits": "Qian Xie and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Electrostatics 4: The distance between charges matters (SAM)",
      "description": "<p>With the following model, you can examine how the Coulomb forces are related to the distance between charges.<\/p>\r\n<p>WHAT TO DO: Open screen as wide as you can. 1. There is a charged particle (+)&nbsp; in the container. The slider on the right is used to adjust its vertical position in the container. 2. Adjust the position of the particle. 3. Click \"Shoot an electron.\" 4. Observe the trajectory of the electron. 5. Adjust the particle in order to get the electron to hit one of the targets.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/electrostatics\/electrostatics-4.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/96.png",
      "credits": "Qian Xie and the Molecular Workbench team;  Model-Builder (Molecular Workbench): Qian Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Electrostatics 5 +: A charge game (SAM)",
      "description": "<p>The goal of this game it to move the white particle to the Target Area before the timer (blue box with the number 10 in the target area) reaches zero. A game employing our understanding of charge:<\/p>\r\n<p>WHAT TO DO: Click Run. Click the button with \"-\" to add a negative charge, \"0\" to neutralize, and \"+\" to add a positive charge to the white particle.  Change the charge as it travels through the maze. Use the Hint button if you run into trouble.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/electrostatics\/electrostatics-5.json",
      "width": 690,
      "height": 340,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/97.png",
      "credits": "QIan Xie and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Diffusion and Osmosis 5: Dynamic Equilibrium   (SAM)",
      "description": "<p>Equilibrium, a state of balance, at the atomic level is dynamic, with atoms and molecules in continual motion. In the diffusion model you can set up various situations such that the concentrations inside and outside of the cell are either out of equilibrium or in equilibrium.<\/p>\r\n<p>WHAT TO DO: FIRST open your screen to full size. Set the concentrations and THEN run.  Reset if necessary. Try some different combinations and see if you can tell when the model reaches equilibrium. You may need to wait for a few minutes, and use the graphs to help you know when equilibrium has been reached.)<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/diffusion\/permeable-membrane.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/123.png",
      "credits": "Dan Damelin and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Diffusion and Osmosis 6: Concentration and breathing (SAM)",
      "description": "<p>Use this model to move a red blood cell into environments with different concentrations of oxygen and observe how the oxygen concentration inside of the red blood cell changes when you put it in different environments (e.g. inside or just after passing through the lung, or at a distant location in an artery).<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/diffusion\/concentration-and-breathing.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/124.png",
      "credits": "Dan Damelin and the Molecular Workbench team; Model-builder (Molecular Workbench): Qian Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Diffusion and Osmosis 12: Osmosis (SAM)",
      "description": "<p>What affects the flow of water into and out of cells? How is osmotic pressure related to salt concentrations (or other dissolved substances?) If you want water to flow out of the cell faster than into the cell, what should you do?  Use the model to explore how the salt concentration inside and outside of the cell affects the flow of water.<\/p>\r\n<p>WHAT TO DO:  1. Set the salt concentrations inside and outside the cell by using the pull-downs below the models. 2. Run the model and observe the levels in the bar graphs. 3. Change the concentrations and observe changes in the osmotic pressure.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/diffusion\/osmosis.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/125.png",
      "credits": "Dan Damelin and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Diffusion and Osmosis 2  - A simple example of diffusion (SAM)",
      "description": "<p>This is a model showing the diffusion of ink in pure water.<\/p>\n<p>WHAT TO DO: 1.&nbsp; Place a drop of food coloring by clicking somewhere in the container. Observe how the dye diffuses.          2. Stop the model. 3. Click the&nbsp; \"show path\" button - the small tangled path at the top of the model - and then click a molecule to discover the path it has taken.. 4. Reset the model and repeat your observations, but place the dye in a different location.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/diffusion\/1-dropping-dye-on-click.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/126.png",
      "credits": "Dan Damelin",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Sandbox: Diffusion of Particles",
      "description": "<p>A \"sand box\" playground for the exploration of diffusion of different sizes of particles. Discover whether temperature affects the rate of diffusion.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/diffusion\/diffusion-sandbox.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/127.png",
      "credits": "Amy Pallant and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Diffusion and Osmosis 4: Designing your own model (SAM)",
      "description": "A simple model of diffusion, in which users may insert different objects in different amounts and observe their diffusion.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/diffusion\/diffusion-build-your-own.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/128.png",
      "credits": "Amy Pallant and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Phase Change 1: Atomic movement in gases (SAM)",
      "description": "<p>A model of several kinds of gases and their interactions.&nbsp;<\/p>\n<p>WHAT TO DO: Run the models of two types of gases and watch them carefully.  The dashed lines represent atom pairs close enough to attract each other. Select \"Show Interactions\". Estimate the average number of dashed lines in the model indicating the weak interactions.&nbsp; (This finding will be useful to compare with interactions in liquids and solids.). Click the \"Randomly pick an atom and show its trajectory\" button to follow an atom.<\/p>\n<p>These findings can be compared with those of Atomic Movement of Liquids and Atomic Movement of Solids.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/states-of-matter\/atomic-movement-in-gases.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/137.png",
      "credits": "Qian Xie and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Phase Change 2: Atomic Movement in Liquids (SAM)",
      "description": "<p>Here are models of two liquids. One liquid is made of atoms only. The other is made of triatomic molecules.<\/p>\n<p>WHAT TO DO: (1) Run the models and watch them carefully. (2) Make sure \"Show Attractions\" is selected. The attractions between atoms are shown by dashed lines. (3) Run each liquid model. (4) Then estimate the average number of dashed lines an atom forms with its neighbors.<\/p>\n<p>These findings can be compared with those of Atomic Movement of Gases and Atomic Movement of Solids.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/states-of-matter\/atomic-movement-in-liquids.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/138.png",
      "credits": "Qian Xie and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Phase Change 3: Atomic Movement in Solids (SAM)",
      "description": "<p>Here are models of two types of solids. Run the models and watch them carefully. WHILE running, press the button \"Randomly pick an atom and show its trajectory.\" It will be highlighted. To see the interactions more clearly, you can change the display style from \"Spacefilling\" to \"Ball-and-Stick\" from the drop-down list below.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/states-of-matter\/atomic-movement-in-solids.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/139.png",
      "credits": "Charles Xie and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Phase Change 5: Phase changes caused by energy Input (SAM)",
      "description": "Can you change the state of matter by adding energy? In this model, atoms are color-coded by their kinetic energy (KE). White means low KE; red means high KE. The left part of the model is filled with a hot liquid (small atoms). The right part is filled with a cold solid (larger atoms). The two parts are separated by a barrier in the middle. Hence, the temperature of the larger atoms will not increase when the wall is in place. \r\nRun the model with the wall for a minute and then hit the \"Withdraw the barrier\" button to remove it. Observe what happens in the model and the bar graph on the right, which records the average kinetic energy (representing temperature) of the larger atoms.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/states-of-matter\/phase-changes-caused-by-energy-input.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/140.png",
      "credits": "Qian Xie and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Phase Change 6: Latent Heat (SAM)",
      "description": "<p>This model shows a small hexagonal crystal that can be heated, revealing the latent heat phenomenon.<\/p>\r\n<p>WHAT TO DO: Press the \"Start heating\" button to begin the simulation and heat it up gradually (imagine using a heat radiator). The model will stop running automatically. Watch the simulation until it stops. The two bar graphs in the middle show the kinetic energy (the red one) and the potential energy (the blue one). The line graph on the right shows the temperature as a function of the total energy of the system, which increases over time.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/states-of-matter\/latent-heat2.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/141.png",
      "credits": "Qian Xie and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Phase Change: Latent Heat and Cooling  (Molo)",
      "description": "",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/states-of-matter\/latent-heat3.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/142.png",
      "credits": "",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Phase Change 4: Attractions and phases (SAM)",
      "description": "<p>This is an experiment to see how changing the force of attraction between molecules affects the state of that material. Use the model to explore this question. You can use the slider to change how strong the forces are between atoms. (This really amounts to changing the type of atom!)  The temperature of this model is kept constant at 300K, about room temperature. It will not warm up, but changing the forces of attraction can change the states of matter.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/states-of-matter\/interatomic-interactions-and-states.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/143.png",
      "credits": "Qian Xie and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Phase Change 8: Evaporation - A more realistic model (SAM)",
      "description": "<p>In this model we put many molecules in a container, which is initially covered from the top to prevent evaporation.<\/p>\r\n<p>WHAT TO DO: Run the model for a while and observe the bar graph on the right, which represents temperature of the system. Then press the \"Remove the cover. Let it evaporate\" button and observe changes of the bar graph.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/states-of-matter\/page8-1.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/144.png",
      "credits": "The Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Heat and Temperature 1: Introduction to heat and molecular movement - Seasons (SAM)",
      "description": "<p>This set of models introduces the theme of heat and temperature.<\/p>\r\n<p>WHAT TO DO: Click an image to see how air molecules move in different seasons. A thermometer on the right measures the corresponding temperature.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/heat-and-temperature\/heat-and-temperature-1.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/145.png",
      "credits": "Dan Damelin and the Molecular Workbench team; Model-builder (Molecular Workbench team): Qian Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Heat and Temperature 4:  Mixing hot and cold (SAM)",
      "description": "<p>This model allows students to explore the flow of particles of different temperatures.<\/p>\r\n<p>WHAT TO DO: Click the \"Run\" button to start, wait until the controls become available, and observe what happens to the bar graphs when the passage between the chambers open. Click the four buttons on the first row to heat or cool a chamber WHILE letting the model run, and watch how the temperature changes.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/heat-and-temperature\/heat-and-temperature-4.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/146.png",
      "credits": "Dan Damelin and the Molecular Workbench team; Model-builder (Molecular Workbench team): Qian Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Heat and Temperature 2: Temperature is related to kinetic energy, not speed (SAM)",
      "description": "<p>Users place 4 different substances, composed of atoms with different masses, in the container. The model will hold the temperature constant for each substance. What differs?<\/p>\r\n<p>WHAT TO DO: Model 1: Experiment with the 4 substances Model 2: Click the \"Run\" button first and let the model run for a while. Observe the bar graphs and the average lengths of the arrows for each type of atom.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/heat-and-temperature\/heat-and-temperature-2.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/147.png",
      "credits": "Dan Damelin and the Molecular Workbench team; Model-builder (Molecular Workbench team): Qian Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Heat and Temperature 2a : Mass and Kinetic Energy (SAM)",
      "description": "<p>How is mass related to the kinetic energy of atoms - and hence to temperature? WHAT<\/p>\r\n<p>TO DO: 1. Click the \"Run\" button first and let the model run for a while. 2. Observe the bar graphs and the average lengths of the arrows for each type of atom.<\/p>\r\n<p>&nbsp;<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/heat-and-temperature\/heat-and-temperature-2a.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/148.png",
      "credits": "The Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Crystals: Introduction to crystals (MOLO)",
      "description": "<p>A model of a solid crystal.<\/p>\r\n<p>WHAT TO DO: Run the model.&nbsp; Heat the crystal by pressing the red caret on the \"thermometer.\"&nbsp; Can you cool it back into a crystal of the same shape?<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/crystal\/crystal_intro2.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/156.png",
      "credits": "Dalit Levy and the Molecular Workbench team; Molecular Workbench: Qian Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Crystals: Introduction to crystals - Far and Near Atoms (MOLO)",
      "description": "<p>This model represents a solid crystal adding atoms to its structure with attractive forces.<\/p>\r\n<p>WHAT TO DO:&nbsp; Add a near atom and a far atom and run the model.&nbsp; What does this imply about crystal growth?<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/crystal\/crystal_intro_far_and_near.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/157.png",
      "credits": "Dalit Levy and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Crystals: Defects  (Molecular Logic Project) ",
      "description": "<p>There are several types of imperfection in crystals; the simplest type is called a \"point defect\". Point defects are important to avoid in making the silicon wafers of semiconductors.&nbsp; There are three important types of point defects: <br \/>&nbsp;- vacancies - a missing atom <br \/>&nbsp;- interstitials - atoms which occupy a site in the crystal structure at which there is usually not an atom.&nbsp; <br \/>&nbsp;- substitutionals - a different species of atom that is incorporated in the crystal structure<\/p>\r\n<p>WHAT TO DO: Locate each type of defect.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/crystal\/crystal_intro6.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/158.png",
      "credits": "Charles Xie, Dan Damelin and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "ER 1: Five flowerpots, one plant",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/populations\/five-sunlight-one-plant.html",
      "width": 700,
      "height": 570,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/539.png",
      "credits": "Paul Horwitz and Sam Fentress",
      "model_type": "Evolution Readiness"
    },
    {
      "name": "ER 2: Five flowerpots, three plants",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/populations\/five-sunlight-three-plants.html",
      "width": 700,
      "height": 570,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/540.png",
      "credits": "Paul Horwitz and Sam Fentress",
      "model_type": "Evolution Readiness"
    },
    {
      "name": "ER 3: Three flowerpots with variation",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/populations\/three-sunlight.html",
      "width": 700,
      "height": 540,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/541.png",
      "credits": "Paul Horwitz and Sam Fentress",
      "model_type": "Evolution Readiness"
    },
    {
      "name": "ER 4: Plant variation with mountains",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/populations\/mountain-sunlight-variation.html",
      "width": 1220,
      "height": 590,
      "scale": 0.72,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/542.png",
      "credits": "Paul Horwitz and Sam Fentress",
      "model_type": "Evolution Readiness"
    },
    {
      "name": "ER 5: Five flower pots with water",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/populations\/five-water-three-plants.html",
      "width": 690,
      "height": 630,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/543.png",
      "credits": "Paul Horwitz and Sam Fentress",
      "model_type": "Evolution Readiness"
    },
    {
      "name": "ER 6: Field of flowers with water",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/populations\/field-water-one-plant-variation.html",
      "width": 950,
      "height": 810,
      "scale": 0.85,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/544.png",
      "credits": "Paul Horwitz and Sam Fentress",
      "model_type": "Evolution Readiness"
    },
    {
      "name": "ER 7: Single rabbit (controllable)",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/populations\/rabbit-controllable.html",
      "width": 700,
      "height": 820,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/545.png",
      "credits": "Paul Horwitz and Sam Fentress",
      "model_type": "Evolution Readiness"
    },
    {
      "name": "ER 8: Rabbit population (controllable)",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/populations\/rabbit-controllable-multi.html",
      "width": 700,
      "height": 820,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/546.png",
      "credits": "Paul Horwitz and Sam Fentress",
      "model_type": "Evolution Readiness"
    },
    {
      "name": "ER 10: Dam model",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/populations\/dam-plants-rabbits.html",
      "width": 1080,
      "height": 550,
      "scale": 0.75,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/548.png",
      "credits": "Paul Horwitz and Sam Fentress",
      "model_type": "Evolution Readiness"
    },
    {
      "name": "ER 11: Reverse dam model",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/populations\/dam-plants-rabbits-reverse.html",
      "width": 1080,
      "height": 550,
      "scale": 0.75,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/549.png",
      "credits": "Paul Horwitz and Sam Fentress",
      "model_type": "Evolution Readiness"
    },
    {
      "name": "ER 12: Hawk and rabbits (controllable)",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/populations\/hawk-controllable.html",
      "width": 700,
      "height": 820,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/550.png",
      "credits": "Paul Horwitz and Sam Fentress",
      "model_type": "Evolution Readiness"
    },
    {
      "name": "ER 13: Hawks and rabbits in changing environment",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/populations\/hawk-rabbit-evolution.html",
      "width": 700,
      "height": 820,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/551.png",
      "credits": "Paul Horwitz and Sam Fentress",
      "model_type": "Evolution Readiness"
    },
    {
      "name": "ER 16: Open model, grass rabbits, hawks and foxes",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/populations\/super-model-foxes-open.html",
      "width": 1270,
      "height": 550,
      "scale": 0.62,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/554.png",
      "credits": "Paul Horwitz and Sam Fentress",
      "model_type": "Evolution Readiness"
    },
    {
      "name": "ER 2.5: Five flowerpots, three plants with graph",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/populations\/five-sunlight-three-plants-graph.html",
      "width": 1200,
      "height": 570,
      "scale": 0.67,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/556.png",
      "credits": "Paul Horwitz and Sam Fentress",
      "model_type": "Evolution Readiness"
    },
    {
      "name": "ER: Field with three plants, no variation",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/populations\/field-three-plants-breed-true.html",
      "width": 1200,
      "height": 780,
      "scale": 0.67,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/557.png",
      "credits": "Paul Horwitz and Sam Fentress",
      "model_type": "Evolution Readiness"
    },
    {
      "name": "ER: Field with one plant, variation",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/populations\/field-one-plant-variation.html",
      "width": 1200,
      "height": 770,
      "scale": 0.67,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/558.png",
      "credits": "Paul Horwitz and Sam Fentress",
      "model_type": "Evolution Readiness"
    },
    {
      "name": "Dissociation_energy",
      "description": "<p>Chemical reaction is about making and breaking chemical bonds. This model shows the simplest chemical reaction --- the dissociation and recombination of diatomic molecules (such as H2, O2, Cl2 and so on). When the temperature rises, the diatomic bonds start to break, producing free radicals. When the temperature drops, the free radical starts to recombine and form diatomic bonds again. To provide the energy for dissociation and maintain the thermal stability of the recombined molecules, a heat bath is applied.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/chemical-reactions\/dissocation-rites.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/597.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Making and Breaking Bonds: A + B -->AB with no temperature slider",
      "description": "<p>This activity supports exploring the making of bonds between two species of atoms.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/chemical-reactions\/making-breaking-ab.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/598.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Convection #1",
      "description": "<p>Convection with movable barriers<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/energy2d\/S4B1.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/601.png",
      "credits": "Charles Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Blowing wind",
      "description": "<p>infiltration heat loss from a building due to wind<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/energy2d\/S4E1.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/603.png",
      "credits": "Charles Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Forced convection",
      "description": "<p>heat loss with and without a fan<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/energy2d\/S4C1.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/604.png",
      "credits": "Charles Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Leaking building",
      "description": "<p>Leaks from a building due to stack effect<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/energy2d\/S4D1.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/605.png",
      "credits": "Charles Xie",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "PhET Balloons and Static Electricity",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/phet\/balloons-and-static-electricity\/balloons-and-static-electricity_en-3.html",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/613.png",
      "credits": "PhET HTML5",
      "model_type": "PhET"
    },
    {
      "name": "Cell Reproductions",
      "description": "<p>Interactive mitosis and meiosis<\/p>",
      "url": "https:\/\/www.nottingham.ac.uk\/nursing\/sonet\/rlos\/bioproc\/celldivision\/mitosis.html",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": " ",
      "credits": "\u00a9 2005 School of Nursing and Academic Division of Midwifery, University of Nottingham  Developer: Dr Viv Rolfe ",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "DNA Mutation I ",
      "description": "<p>AAATTTGGGCCCATGCTAGCTATAGTAGTA DNA sequence<\/p>\n<p>(DNA to Proteins: Making mutations (SAM))<\/p>\n<p>&nbsp;<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/protein-structure\/isti-mutations-1.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/mw\/dna_mutation\/dna_mutation_1_new.jpg",
      "credits": "Boris Berenfeld and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "DNA Mutation II",
      "description": "<p>TTTCCCTTTGGGCCCTTTAAATTTGGG sequence<\/p>\n<p>(DNA to Proteins: Making mutations (SAM))<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/protein-structure\/isti-mutations-2.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/mw\/dna_mutation\/dna_mutation_2_new.jpg",
      "credits": "Boris Berenfeld and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "DNA Mutation III",
      "description": "<p>AGATTTGGGCTCATGCTAGCTATAGTACTT sequence<\/p>\n<p>(DNA to Proteins: Making mutations (SAM))<\/p>\n<p>&nbsp;<\/p>\n<p>&nbsp;<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/protein-structure\/isti-mutations-3.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/mw\/dna_mutation\/dna_mutation_3_new.jpg",
      "credits": "Boris Berenfeld and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "DNA Mutation IV",
      "description": "<p>AGATTTGGGCTCATGCTAGCTATAGTAGTA sequence<\/p>\n<p>(DNA to Proteins: Making mutations (SAM))<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/protein-structure\/isti-mutations-4.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/mw\/dna_mutation\/dna_mutation_4_new.jpg",
      "credits": "Boris Berenfeld and the Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "ER 4: Plant variation with mountains (chart)",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/populations\/mountain-sunlight-variation-chart.html",
      "width": 1200,
      "height": 590,
      "scale": 0.72,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/625.png",
      "credits": "Paul Horwitz and Sam Fentress",
      "model_type": "Evolution Readiness"
    },
    {
      "name": "PhET Acid-Base Solutions: Custom Solution",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/phet\/acid-base-solutions\/acid-base-solutions_en.html?screenIndex=1&standalone=true",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/626.png",
      "credits": "PhET HTML5",
      "model_type": "PhET"
    },
    {
      "name": "PhET Beer's Law Lab: Concentration",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/phet\/beers-law-lab\/beers-law-lab_en.html?screenIndex=0&standalone=true",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/627.png",
      "credits": "PhET HTML5",
      "model_type": "PhET"
    },
    {
      "name": "PhET pH Scale: Basics",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/phet\/ph-scale-basics\/ph-scale-basics_en.html",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/628.png",
      "credits": "PhET HTML5",
      "model_type": "PhET"
    },
    {
      "name": "PhET pH Scale: Macro",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/phet\/ph-scale\/ph-scale_en.html?screenIndex=0&standalone=true",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/629.png",
      "credits": "PhET HTML5",
      "model_type": "PhET"
    },
    {
      "name": "PhET Molarity",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/phet\/molarity\/molarity_en.html",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/630.png",
      "credits": "PhET HTML5",
      "model_type": "PhET"
    },
    {
      "name": "PhET Acid-Base Solutions: Introduction",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/phet\/acid-base-solutions\/acid-base-solutions_en.html?screenIndex=0&standalone=true",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/631.png",
      "credits": "PhET HTML5",
      "model_type": "PhET"
    },
    {
      "name": "PhET Beer's Law Lab: Beer's Law",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/phet\/beers-law-lab\/beers-law-lab_en.html?screenIndex=1&standalone=true",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/632.png",
      "credits": "PhET HTML5",
      "model_type": "PhET"
    },
    {
      "name": "PhET pH Scale: Micro",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/phet\/ph-scale\/ph-scale_en.html?screenIndex=1&standalone=true",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/633.png",
      "credits": "PhET HTML5",
      "model_type": "PhET"
    },
    {
      "name": "PhET pH Scale: Custom",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/phet\/ph-scale\/ph-scale_en.html?screenIndex=2&standalone=true",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/634.png",
      "credits": "PhET HTML5",
      "model_type": "PhET"
    },
    {
      "name": "PhET Energy Skate Park: Basics: Intro",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/phet\/energy-skate-park-basics\/energy-skate-park-basics_en.html?screenIndex=0&standalone=true",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/635.png",
      "credits": "PhET HTML5",
      "model_type": "PhET"
    },
    {
      "name": "PhET Energy Skate Park: Basics: Friction",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/phet\/energy-skate-park-basics\/energy-skate-park-basics_en.html?screenIndex=1&standalone=true",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/636.png",
      "credits": "PhET HTML5",
      "model_type": "PhET"
    },
    {
      "name": "PhET Energy Skate Park: Basics: Playground",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/phet\/energy-skate-park-basics\/energy-skate-park-basics_en.html?screenIndex=2&standalone=true",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/637.png",
      "credits": "PhET HTML5",
      "model_type": "PhET"
    },
    {
      "name": "Double Pendulum",
      "description": "Double Pendulum",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/inquiry-examples\/pendulum\/4-double-pendulum1.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/639.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Pendulum",
      "description": "Explore some factors that affect the period of a pendulum.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/inquiry-space\/pendulum\/1-pendulum.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/640.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Spring &amp; Mass",
      "description": "Explore some factors that affect the period of a spring.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/inquiry-space\/pendulum\/2-spring.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/641.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Pendulum &amp; Spring",
      "description": "Explore the motion of a pendulum on a spring.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/inquiry-space\/pendulum\/3-springy-pendulum.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/642.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Visualizing Electric Fields and Forces",
      "description": "Visualizing Electric Fields and Forces",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/interactions\/act2model.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/643.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Charge Intensity and Electric Force",
      "description": "Charge Intensity and Electric Force",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/interactions\/amount-charge.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/644.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Opposites Attract",
      "description": "Opposites Attract",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/interactions\/chargeballs.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/645.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Direction of Force on Charged Objects",
      "description": "Direction of Force on Charged Objects",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/interactions\/forceDirection.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/646.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Direction of Force Around a VDG (Negatively Charged)",
      "description": "Direction of Force Around a VDG (Negatively Charged)",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/interactions\/forceDirectionVDGnegative.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/647.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Direction of Force Around a VDG (Positively Charged)",
      "description": "Direction of Force Around a VDG (Positively Charged)",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/interactions\/forceDirectionVDGpositive.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/648.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Direction and Strength of Force in Electric Fields",
      "description": "Direction and Strength of Force in Electric Fields",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/interactions\/forceStrengthDirection.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/649.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Mixing Liquids",
      "description": "Mixing Liquids",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/interactions\/particleMixing.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/650.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Gas Pressure in a Syringe",
      "description": "Gas Pressure in a Syringe",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/interactions\/syringe.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/651.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Target Game (Free Play)",
      "description": "Target Game (Free Play)",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/interactions\/targetFreePlay.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/652.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Target Game (Charge Magnitude \/ Force Relationship)",
      "description": "Target Game (Charge Magnitude \/ Force Relationship)",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/interactions\/targetGameCharge.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/653.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Target Game (Distance\/Force Relationship)",
      "description": "Target Game (Distance\/Force Relationship)",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/interactions\/targetGameDist.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/654.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Electron Geometry",
      "description": "Electron Geometry",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/jsmol\/electron-geometry.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/655.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Energy Levels of a Hydrogen Atom",
      "description": "Energy Levels of a Hydrogen Atom",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/jsmol\/energy-levels.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/656.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "DNA: The Double Helix",
      "description": "DNA: The Double Helix",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/jsmol\/jsmol-dna.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/657.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Aquapores",
      "description": "Aquapores",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/jsmol\/porous-membrane.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/658.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Unshared Electrons and the \"Bent\" Shape",
      "description": "Unshared Electrons and the 'Bent' Shape",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/jsmol\/unshared-electrons.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/659.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "What is a Chemical Reaction? ",
      "description": "What is a Chemical Reaction? ",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/chemical-reactions\/1-what-is-a-chemical-reaction.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/660.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Temperature and Reaction Rate",
      "description": "Temperature and Reaction Rate",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/chemical-reactions\/3-temperature-and-reaction-rate.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/661.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Stoichiometry and Balancing Equations",
      "description": "Stoichiometry and Balancing Equations",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/chemical-reactions\/4-stoichiometry-and-balancing-equations.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/662.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Catalysis",
      "description": "Catalysis",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/chemical-reactions\/6-catalysis.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/663.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Polymers and Monomers",
      "description": "Polymers and Monomers",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/chemical-reactions\/7-polymers-monomers.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/664.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Diffusion &amp; Temperature",
      "description": "How does temperature affect the rate of diffusion?",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/diffusion\/2-temperature.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/665.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Diffusion &amp; Molecular Mass",
      "description": "How does molecular mass affect the rate of diffusion?",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/diffusion\/3-mass.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/666.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Diffusion Across Semipermeable Membranes",
      "description": "How does pore size affect the diffusion of different molecules?",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/diffusion\/4-2-semipermeable-two-barrier.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/667.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Diffusion Across a Semipermeable Membrane",
      "description": "How does pore size affect the diffusion of different molecules?",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/diffusion\/4-semipermeable.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/668.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "DNA to Protein",
      "description": "<p>Explore how the code embedded in DNA is translated into a protein.<\/p>",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/DNA-to-proteins\/1-dna-to-protein.json",
      "width": 690,
      "height": 585,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/669.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Modeling Transcription",
      "description": "Explore how an mRNA copy is made of DNA.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/DNA-to-proteins\/2-modeling-transcription.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/670.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Modeling Translation",
      "description": "Explore how a protein is made from an mRNA sequence.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/DNA-to-proteins\/3-modeling-translation.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/671.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "The Volume-Pressure Relationship",
      "description": "Explore how the volume of a gas affects pressure.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/gas-laws\/3-volume-pressure-relationship.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/672.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "The Temperature-Volume Relationship",
      "description": "Investigate the relationship between temperature and the volume of a gas.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/gas-laws\/4-temperature-volume-relationship.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/673.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Seeing Intermolecular Attractions",
      "description": "All matter is attracted to all other matter. How does this work?",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/intermolecular-attractions\/1-introduction.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/674.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Comparing Dipole-Dipole to London Dispersion",
      "description": "Explore the difference in attractive forces between polar and non-polar molecules.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/intermolecular-attractions\/2-comparing-dipole-dipole-to-london-dispersion.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/675.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Oil and Water",
      "description": "Explore how polar and non-polar substances interact.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/intermolecular-attractions\/3-1-oil-and-water.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/676.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Boiling Point",
      "description": "Explore what boiling looks like at the molecular level with both polar and non-polar substances.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/intermolecular-attractions\/3-2-boiling-point-and-solubility.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/677.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Polarity and Attractive Strength",
      "description": "Explore the different attractive forces between molecules of varying polarity.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/intermolecular-attractions\/4-strengthening-dipole-dipole-attractions.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/678.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Factors Affecting London Dispersion Attractions",
      "description": "Explore how differences in molecular size and shape affect the strength of London Dispersion attractions.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/intermolecular-attractions\/5-strengthening-london-dispersion-attraction.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/679.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Hydrogen Bonds: A Special Type of Attraction",
      "description": "Explore how polar molecules interact via hydrogen bonds.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/intermolecular-attractions\/6-hydrogen-bonds-a-special-type-of-attraction.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/680.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Excited Electrons",
      "description": "Excited Electrons",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/light-matter\/excited-states-and-photons-page-2.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/681.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Different Excited States for Different Elements",
      "description": "Different Excited States for Different Elements",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/light-matter\/excited-states-and-photons-page-3.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/682.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Sunlight, Infrared, CO2 and the Ground",
      "description": "Sunlight, Infrared, CO2 and the Ground",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/light-matter\/sun-on-ground.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/683.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Molecular View of a Gas",
      "description": "Explore how molecules in a gas move relative to each other.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/phase-change\/2-two-types-of-gases.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/684.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Molecular View of a Liquid",
      "description": "Explore how molecules in a liquid move.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/phase-change\/3-liquids.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/685.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Molecular View of a Solid",
      "description": "What does a solid look like at the molecular level?",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/sam\/phase-change\/4-solids.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/686.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Charged and Neutral Atoms",
      "description": "Explore Coulomb and intermolecular attractions.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/samples\/3-100-atoms.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/687.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Charged and Neutral Atoms (conceptual version)",
      "description": "Explore Coulomb and intermolecular attractions.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/samples\/4-100-atoms-conceptual.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/688.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Protein Folding",
      "description": "How do peptides fold into stable conformations?",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/samples\/5-amino-acids.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/689.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Ceramic Forces",
      "description": "Explore how the molecular structure of ceramic affects its mechanical properties.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/visual\/recycling\/1-ceramicforces.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/690.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Metal Forces",
      "description": "Explore how the molecular structure of metal affects its mechanical properties.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/visual\/recycling\/2-metalforces.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/691.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Plastic Forces",
      "description": "Explore how the molecular structure of plastic affects its mechanical properties.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/visual\/recycling\/3-plasticforces.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/692.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Tire Forces",
      "description": "Explore how the molecular structure of tire rubber affects its mechanical properties.",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/visual\/recycling\/4-tireforces.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/693.png",
      "credits": "Molecular Workbench team",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "PhET pH Scale: Basics (hidden pH)",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/phet\/ph-scale-basics-hidden-ph\/ph-scale-basics_en.html",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/694.png",
      "credits": "PhET HTML5",
      "model_type": "PhET"
    },
    {
      "name": "PhET pH Scale: Macro (hidden pH)",
      "description": "",
      "url": "https:\/\/models-resources.concord.org\/phet\/ph-scale-hidden-ph\/ph-scale_en.html?screenIndex=0&standalone=true",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/695.png",
      "credits": "PhET HTML5",
      "model_type": "PhET"
    },
    {
      "name": "HAS: Air Pollution",
      "description": "<p>Air Pollution<\/p>",
      "url": "https:\/\/s3.amazonaws.com\/models-resources\/agentscript\/air-pollution\/index.html",
      "width": 980,
      "height": 590,
      "scale": 0.71,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/696.png",
      "credits": "HAS",
      "model_type": "Custom OTrunk"
    },
    {
      "name": "HAS: Fracking",
      "description": "<p>Fracking<\/p>",
      "url": "https:\/\/s3.amazonaws.com\/models-resources\/agentscript\/fracking\/fracking-3.html",
      "width": 980,
      "height": 520,
      "scale": 0.71,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/697.png",
      "credits": "HAS",
      "model_type": "Custom OTrunk"
    },
    {
      "name": "HAS: Global Climate (Ocean)",
      "description": "",
      "url": "https:\/\/s3.amazonaws.com\/models-resources\/agentscript\/global-climate\/global-climate-ocean.html",
      "width": 980,
      "height": 590,
      "scale": 0.71,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/698.png",
      "credits": "HAS",
      "model_type": "Custom OTrunk"
    },
    {
      "name": "HAS: Water",
      "description": "",
      "url": "https:\/\/s3.amazonaws.com\/models-resources\/agentscript\/water\/index.html",
      "width": 830,
      "height": 500,
      "scale": 0.83,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/699.png",
      "credits": "HAS",
      "model_type": "Custom OTrunk"
    },
    {
      "name": "HAS: Land Management",
      "description": "",
      "url": "https:\/\/s3.amazonaws.com\/models-resources\/agentscript\/land-management\/index.html",
      "width": 980,
      "height": 570,
      "scale": 0.71,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/700.png",
      "credits": "HAS",
      "model_type": "Custom OTrunk"
    },
    {
      "name": "Surface Water Video",
      "description": "",
      "url": "http:\/\/itsisu.concord.org\/share\/water-movies\/surface-water.html",
      "width": 383,
      "height": 287,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/water-movies\/_assets\/img\/surface-water-383x287.jpg",
      "credits": "",
      "model_type": "Video"
    },
    {
      "name": "iSENSE Turbidity",
      "description": "",
      "url": "http:\/\/concord-consortium.github.io\/iSENSE-interactive\/#862",
      "width": 700,
      "height": 700,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/isense.png",
      "credits": "UMass Lowell\/Concord Consortium ",
      "model_type": "iSENSE"
    },
    {
      "name": "iSENSE Nitrate",
      "description": "<p>iSENSE Nitrate data collector<\/p>",
      "url": "http:\/\/concord-consortium.github.io\/iSENSE-interactive\/#863",
      "width": 700,
      "height": 700,
      "scale": 1,
      "image_url": "http:\/\/isenseproject.org\/assets\/isense-logo-fa466f64919add7f5fb36fd2e9741f08.png",
      "credits": "UMass Lowell\/Concord Consortium",
      "model_type": "iSENSE"
    },
    {
      "name": "iSENSE Temperature Difference",
      "description": "<p>iSENSE Temperature Difference<\/p>",
      "url": "http:\/\/concord-consortium.github.io\/iSENSE-interactive\/#864",
      "width": 700,
      "height": 700,
      "scale": 1,
      "image_url": "http:\/\/isenseproject.org\/assets\/isense-logo-fa466f64919add7f5fb36fd2e9741f08.png",
      "credits": "UMass Lowell\/Concord Consortium",
      "model_type": "iSENSE"
    },
    {
      "name": "iSENSE Dissolved Oxygen (DO) and Temperature",
      "description": "<p>iSENSE Dissolved Oxygen (DO) and Temperature<\/p>",
      "url": "http:\/\/concord-consortium.github.io\/iSENSE-interactive\/#866",
      "width": 700,
      "height": 700,
      "scale": 1,
      "image_url": "http:\/\/isenseproject.org\/assets\/isense-logo-fa466f64919add7f5fb36fd2e9741f08.png",
      "credits": "UMass Lowell\/Concord Consortium ",
      "model_type": "iSENSE"
    },
    {
      "name": "iSENSE pH",
      "description": "<p>iSENSE pH<\/p>",
      "url": "http:\/\/concord-consortium.github.io\/iSENSE-interactive\/#867",
      "width": 700,
      "height": 700,
      "scale": 1,
      "image_url": "http:\/\/isenseproject.org\/assets\/isense-logo-fa466f64919add7f5fb36fd2e9741f08.png",
      "credits": "UMass Lowell\/Concord Consortium ",
      "model_type": "iSENSE"
    },
    {
      "name": "iSENSE Dissolved Oxygen (DO) and pH",
      "description": "<p>iSENSE Dissolved Oxygen (DO) and pH throughout the day<\/p>",
      "url": "http:\/\/concord-consortium.github.io\/iSENSE-interactive\/#868",
      "width": 700,
      "height": 700,
      "scale": 1,
      "image_url": "http:\/\/isenseproject.org\/assets\/isense-logo-fa466f64919add7f5fb36fd2e9741f08.png",
      "credits": "UMass Lowell\/Concord Consortium ",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Water Videos",
      "description": "",
      "url": "http:\/\/staff.concord.org\/~emcelroy\/water-videos\/video.html",
      "width": 720,
      "height": 720,
      "scale": 0.75,
      "image_url": "http:\/\/staff.concord.org\/~emcelroy\/water-videos\/_assets\/img\/placeholder.jpg",
      "credits": "",
      "model_type": "Video"
    },
    {
      "name": "Water Videos 2",
      "description": "",
      "url": "http:\/\/staff.concord.org\/~emcelroy\/water-videos\/video.html",
      "width": 720,
      "height": 720,
      "scale": 0.75,
      "image_url": "http:\/\/staff.concord.org\/~emcelroy\/water-videos\/_assets\/img\/placeholder.jpg",
      "credits": "",
      "model_type": "Video"
    },
    {
      "name": "Testing Model Interactive by Zeus",
      "description": "<p>Test test<\/p>",
      "url": "\/\/ https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/energy2d\/conduction-temperature-difference.jso",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/12.png",
      "credits": "Test Credits",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Test Interactive 1",
      "description": "Test",
      "url": "",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "",
      "credits": "",
      "model_type": null
    },
    {
      "name": "Oil and Water - Jen",
      "description": "Just testing",
      "url": "http:\/\/lab.concord.org\/embeddable.html#interactives\/samples\/1-oil-and-water-shake.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "",
      "credits": "",
      "model_type": "Molecular Workbench"
    },
    {
      "name": "Test AuthoredbyMe Interactive",
      "description": "Test AuthoredbyMe Interactive",
      "url": "https:\/\/lab.concord.org\/embeddable.html#interactives\/itsi\/heat-and-temperature\/heat-and-temperature-7.json",
      "width": 690,
      "height": 400,
      "scale": 1,
      "image_url": "http:\/\/itsisu.concord.org\/share\/model_images\/12.png",
      "credits": "",
      "model_type": null
    }
  ]
