ENV['DEFAULT_AUTH_PROVIDER']         ||= 'concord_portal'
ENV['CONCORD_PORTAL_URL']            ||= 'http://nextgen.staging.concord.org'
ENV['CONCORD_PORTAL_CLIENT_ID']      ||= 'authoring-staging'
ENV['CONCORD_PORTAL_CLIENT_SECRET']  ||= 'XXXXXXXXXXXXXXXXX'
ENV['SECRET_TOKEN']                  ||= 'use `rake secret` to generate'