---
development: &development
  encoding: utf8
  adapter: mysql2
  username: <%= ENV['DB_USER'] || 'root' %>
  database: <%= ENV['DB_NAME'] || 'lara' %>_production
  password: <%= ENV['DB_PASSWORD'] || 'simple' %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  pool: 5


test: &test
  encoding: utf8
  adapter: mysql2
  username: <%= ENV['DB_USER'] || 'root' %>
  database: <%= ENV['DB_NAME'] || 'lara' %>_test
  password: <%= ENV['DB_PASSWORD'] || 'simple' %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  pool: 5

production: *development
