// This file is for Jasmine specs - below was generated by rails g jasmine:examples

// beforeEach(function() {
//   this.addMatchers({
//     toBePlaying: function(expectedSong) {
//       var player = this.actual;
//       return player.currentlyPlayingSong === expectedSong
//           && player.isPlaying;
//     }
//   })
// });
